---
server:
  port: 8081

spring:
  application:
    name: muffin-wallet
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/muffin_wallet
    username: muffin-wallet
  liquibase:
    enabled: true

currency:
  service:
    url: http://muffin-currency:8083/rate

management:
  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans
      connect-timeout: 10s
      read-timeout: 30s
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
