---
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/muffin_wallet
    username: muffin-wallet
  liquibase:
    enabled: true

currency:
  service:
    url: http://muffin-currency:8083/rate
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
