apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-collector
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
