prometheus:
  enabled: true

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "standard"
          resources:
            requests:
              storage: 20Gi

    retention: 7d
    retentionSize: "20GB"

    scrapeInterval: 30s
    evaluationInterval: 30s

    thanos: {}

    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    probeSelector: {}
    probeNamespaceSelector: {}

    additionalScrapeConfigs: []

# Alertmanager disabled
alertmanager:
  enabled: false

# Grafana enabled
grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  replicaCount: 1

  persistence:
    enabled: true
    type: "pvc"
    size: 5Gi
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard"

  securityContext:
    runAsUser: 472
    fsGroup: 472

  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 120
    timeoutSeconds: 10
    periodSeconds: 15
    failureThreshold: 10

  livenessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 180
    timeoutSeconds: 10
    periodSeconds: 30
    failureThreshold: 5

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring:3100
      isDefault: false
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring:3200
      isDefault: false

# Node exported disabled
prometheus-node-exporter:
  enabled: false

# Kube metrics enabled
kube-state-metrics:
  enabled: true
