tempo:
  livenessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 60
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 30
    timeoutSeconds: 1

persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
