replicaCount: 2

image:
  repository: enzhine/muffin-wallet
  pullPolicy: Always
  tag: "1.2.0"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: muffin-wallet.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: muffin-wallet
              port:
                number: 80
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 120
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 120
  periodSeconds: 10

envFrom:
  - secretRef:
      name: muffin-wallet
  - configMapRef:
      name: muffin-wallet-env

nodeSelector: {}

tolerations: []

affinity: {}

filesConfigMap:
  name: muffin-wallet
  files:
    - "application.yaml"
    - "logback-spring.xml"

envsConfigMap:
  name: muffin-wallet-env
  data:
    JDK_JAVA_OPTIONS: -Dspring.config.additional-location=/app/config/application.yaml -Dlogging.config=file:/app/config/logback-spring.xml

envsSecret:
  name: muffin-wallet
  data:
    SPRING_DATASOURCE_PASSWORD: bXVmZmluLXdhbGxldA==

volumes:
  - name: application-config-volume
    configMap:
      name: muffin-wallet
  - name: alloy-config-volume
    configMap:
      name: muffin-wallet-alloy
  - name: application-logs-volume
    emptyDir: {}

volumeMounts:
  - name: application-config-volume
    mountPath: /app/config
  - name: application-logs-volume
    mountPath: /app/logs

alloy:
  image:
    repository: grafana/alloy
    tag: v1.13.0-rc.2
  volumeMounts:
    - name: alloy-config-volume
      mountPath:  /etc/alloy
    - name: application-logs-volume
      mountPath: /var/log/app
      readOnly: true
  filesConfigMap:
    name: muffin-wallet-alloy
    files:
      - "config.alloy"
