apiVersion: v1
kind: ConfigMap
metadata:
  name: muffin-wallet-liquibase
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete,post-rollback,pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  {{- range .Values.liquibaseConfigMap.files }}
  {{ . }}: |-
    {{- $.Files.Get (printf "files/%s" .) | nindent 4 }}
  {{- end }}
